In [11]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity #find similar songs

In [12]:
raw_df = pd.read_csv("../data/spotify_tracks.csv")
clustered_df = pd.read_csv("../data/spotify_tracks_clustered_moods.csv")

print(raw_df.shape)
print(clustered_df.shape)

(114000, 21)
(114000, 17)

In [13]:
raw_df["cluster"] = clustered_df["cluster"]
raw_df["mood_name"] = clustered_df["mood_name"]

df = raw_df
df.head()

   Unnamed: 0                track_id  ... cluster       mood_name
0           0  5SuOikwiRyPMVoIQDJUgSV  ...       5     Party Beast
1           1  4qPNDBW1i3p13qLCt0Ki3A  ...       1  Acoustic Chill
2           2  1iJBSr7s7jYXzM8EGcbK5b  ...       1  Acoustic Chill
3           3  6lfxq3CG4xtTiEg7opyCyx  ...       1  Acoustic Chill
4           4  5vjLSffimiIP26QG5WcN2K  ...       1  Acoustic Chill

[5 rows x 23 columns]

In [14]:
feature_cols = [
    "danceability",
    "energy",
    "valence",
    "acousticness",
    "instrumentalness",
    "speechiness",
    "liveness",
    "tempo"
]

In [15]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[feature_cols])

In [ ]:
# #TO BUILD SIMILARITY SYSTEM WE HAVE 2 OPTIONS:
# 1. COSINE : Measures similarity based on angle (pattern similarity).✅
# 2. EUCLIDEAN

In [17]:
print(df.columns)

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre', 'cluster', 'mood_name'],
      dtype='str')

In [18]:
# FIRST WE WILL Build Recommendation Function
def recommend_similar_songs(song_name, top_n=5):
    # find matching song
    matches = df[df["track_name"].str.lower() == song_name.lower()]

    if matches.empty:
        return "Song not found. Please check spelling."

    song_index = matches.index[0]

    # get cluster of that song
    song_cluster = df.loc[song_index, "cluster"]

    # filter songs in same cluster
    cluster_indices = df[df["cluster"] == song_cluster].index

    # extract vectors for cluster songs
    cluster_vectors = X_scaled[cluster_indices]

    # extract vector of input song
    song_vector = X_scaled[song_index].reshape(1, -1)

    # cosine similarity
    similarities = cosine_similarity(song_vector, cluster_vectors)[0]

    # sort indices by similarity (descending)
    sorted_idx = np.argsort(similarities)[::-1]

    # get top song indices
    top_song_indices = cluster_indices[sorted_idx]

    # remove input song itself
    top_song_indices = top_song_indices[top_song_indices != song_index]

    # select top N recommendations
    top_song_indices = top_song_indices[:top_n]

    return df.loc[top_song_indices, ["track_name", "artists", "mood_name", "cluster", "popularity"]]

In [19]:
# TO CHECK
recommend_similar_songs("Blinding Lights", top_n=5)

                                     track_name  ... popularity
38541                                  Mob Rule  ...         29
69744                            Vaanampaadiyin  ...         22
88712   (I Can't Help) Falling In Love With You  ...         70
33591                                   Atrakce  ...         36
100553                                   Me Voy  ...         34

[5 rows x 5 columns]

# ##TILL HERE IT WAS RECOMMENDATION SYSTEM, NOW WE'RE GONNA BUILD MOOD BASED RECOMMENDATION SYSTEM
- ✅ Build recommendation system
    Function idea:

    input: song name
    output: top 5 similar songs from same cluster
    (using cosine similarity / euclidean distance)

- ✅ Add a “mood-based recommendation”
    Example:
    Input mood: chill → recommend 10 chill songs

In [24]:
def recommend_by_mood(mood, n=11):
    mood_matches = df[df["mood_name"].str.lower() == mood.lower()]

    if mood_matches.empty:
        return "Mood not found. Please check spelling."

    return mood_matches.sample(n=min(n, len(mood_matches)), random_state=42)[
        ["track_name", "artists", "mood_name", "cluster", "popularity"]
    ]

In [25]:
recommend_by_mood("Acoustic Chill", n=11)

                                           track_name  ... popularity
76921   Ailein Duinn (Theme From The Movie "Rob Roy")  ...         20
11612                                      Daydreamer  ...         51
79746                           I Want You To Love Me  ...         59
12360                                           難得有情人  ...         47
51714                     Kanne Kanne (From "Ayogya")  ...         57
106229                               Piano in the Sky  ...          0
102087         Until I Found You - Em Beihold Version  ...          2
4530                                    October Birds  ...         43
99311                                  Main Toh Chala  ...         42
52771                                 I Saw The Light  ...         11
84657                                          4 + 20  ...         55

[11 rows x 5 columns]